export const GET_RESULTS_REQUESTED = 'GET_RESULTS_REQUESTED';
export const GET_RESULTS_SUCCEEDED = 'GET_RESULTS_SUCCEEDED';
export const GET_RESULTS_FAILED = 'GET_RESULTS_FAILED';
export const GET_PAGE_NUMBER_INCREMENT = 'GET_PAGE_NUMBER_INCREMENT';
export const GET_PAGE_NUMBER_DECREMENT = 'GET_PAGE_NUMBER_DECREMENT';